module.exports = [
  {
    id: 1,
    name: 'Hervé Guillon',
    title: 'Postdoctoral Researcher',
    description:
      'Hervé is a Postdoctoral Scholar at the University of California, Davis working with Dr. Lane and Dr. Samuel Sandoval (UC Davis) to derive a hydro-geomorphic stream classification for multiple hydrologic basins in California. He is using data mining and machine learning techniques to understand landscape and near-stream controls on channel geomorphic settings. Hervé completed his PhD in the Institut des Sciences de la Terre in France on present-day erosion processes in a glaciated catchment in the Mont-Blanc massif. Before coming to UC Davis, Hervé joined the hydrology and glaciology laboratory Institut des Géosciences de l’Environnement in France to discriminate suspended sediment origin from in-situ settling behaviour with optical methods.',
    image: 'https://s3.amazonaws.com/37assets/svn/765-default-avatar.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Herve_Guillon2',
    website: 'https://guillon.xyz',
    email: 'hguillon@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 2,
    name: 'Belize A. Lane',
    title: 'Assistant Professor',
    description:
      "Belize's research is at the intersection of hydrology, river science, and water resources management, with an emphasis on improving river management for both human and environmental objectives. She is interested in linking hydrology, fluvial geomorphology, and river ecology to improve basic scientific understanding of river systems. Belize received her B.S. in Ecology with a minor in Mathematics from the University of California San Diego and M.S. in Water Resources Management from the University of California Davis. Her Ph.D. is in Hydrologic Sciences from UC Davis working with Dr. Samuel Sandoval, Dr. Greg Pasternack, and Dr. Helen Dahlke.",
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/belize.png',
    location: 'Utah State University',
    researchGate: 'https://www.researchgate.net/profile/Belize_Lane',
    website: 'https://belizelane.wixsite.com/wetlab',
    email: 'belize.lane@usu.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 3,
    name: 'Jose Pablo Ortiz Partida',
    title: 'Ph.D. Candidate',
    description:
      'Jose Pablo received a scholarship from the Mexican Government for pursuing a Ph.D. in Hydrologic Sciences at the University of California, Davis. He is interested on Integrated Water Resources Management with an specific focus on water quantity and water quality modelling. He earned his Bachelor’s degree in Environmental Engineering from the Western Institute of Technology and Higher Education (ITESO) in Guadalajara, Jalisco, Mexico. He is working on a water quality modeling for the Big Bend reach of the Rio Grande/Rio Bravo Basin. His dream is to find solutions for the preservation and distribution of water resources to provide people in need access to clean and safe water.',
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/pablo.png',
    location: 'University of California, Davis',
    researchGate:
      'https://www.researchgate.net/profile/Jose_Pablo_Ortiz_Partida',
    email: 'joportiz@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 4,
    name: 'Gregory B. Pasternack',
    title: 'Associate Professor',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/greg.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Gregory_Pasternack',
    youtube: 'https://www.youtube.com/channel/UCAZOB4DrcgfBmH3PtySSJew',
    email: 'gpast@ucdavis.edu',
    googleScholar:
      'https://scholar.google.com/citations?hl=en&user=PSIXjQoAAAAJ',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 5,
    name: 'Noelle Patterson',
    title: 'MS Hydrologic Sciences',
    description:
      'Noelle is pursuing a Masters in Hydrologic Sciences at the University of California, Davis, co-advised with Dr. Sandoval. After two years of working in water quality policy at the California State Water Board, Noelle was eager to join in research that helps inform sustainable management of water resources. Her research primarily focuses on flow requirements to preserve ecological function of regulated rivers. Noelle received her bachelor’s degree in Biological Systems Engineering from UC Davis.',
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/noelle.png',
    location: 'University of California, Davis',
    linkedin: 'https://www.linkedin.com/in/noelle-patterson-8311b0b0/',
    github: 'https://github.com/NoellePatterson',
    email: 'nkpatterson@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 6,
    name: 'Leo Qiu',
    title: 'Software Engineer',
    description:
      'Leo is a full stack software developer working with Python and Javascript. As a web developer and programmer for the eFlows project, Leo works to communicate environmental data in clear and interactive platform.',
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/leo.png',
    location: 'University of California, Davis',
    linkedin: 'https://www.linkedin.com/in/leo-qiu/',
    github: 'https://github.com/leogoesger/',
    email: 'leoq91@gmail.com',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 7,
    name: 'Samuel Sandoval-Solis',
    title: 'Associate Professor',
    description:
      'Samuel is an associate professor and cooperative extension specialist. His expertise is in water resources planning and management. During decision making process, Samuel is the person working between the scientists, engineers, environmentalists, system operators and decision makers; he integrates ideas into policies and quantifies benefits and drawbacks. Samuel shares his expertise and passion for quantitative water planning with students through his course entitled Water, Science and Management (ESM-121) in which he demonstrates to student tools and methods to design sustainable water resources systems.',
    image: 'https://eflow.nyc3.digitaloceanspaces.com/resources/sam.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Samuel_Sandoval-Solis',
    email: 'samsandoval@ucdavis.edu',
    youtube: 'https://www.youtube.com/channel/UCyBwkhlzzHjVnGnDnBV5hqw',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
];
