module.exports = [
  {
    id: 1,
    name: 'Belize A. Lane',
    title: 'Assistant Professor',
    description:
      "Belize's research is at the intersection of hydrology, river science, and water resources management, with an emphasis on improving river management for both human and environmental objectives. She is interested in linking hydrology, fluvial geomorphology, and river ecology to improve basic scientific understanding of river systems. Belize received her B.S. in Ecology with a minor in Mathematics from the University of California San Diego and M.S. in Water Resources Management from the University of California Davis. Her Ph.D. is in Hydrologic Sciences from UC Davis working with Dr. Samuel Sandoval, Dr. Greg Pasternack, and Dr. Helen Dahlke.",
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/belize.png',
    location: 'Utah State University',
    researchGate: 'https://www.researchgate.net/profile/Belize_Lane',
    website: 'https://www.usuwetlab.org/',
    email: 'belize.lane@usu.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 2,
    name: 'Noelle Patterson',
    title: 'MS Hydrologic Sciences',
    description:
      'Noelle is pursuing a Masters in Hydrologic Sciences at the University of California, Davis, co-advised Drs. Samuel Sandoval and Belize Lane. After two years of working in water quality policy at the California State Water Board, Noelle was eager to join in research that helps inform sustainable management of water resources. Her research focuses on flow requirements to preserve ecological function of regulated rivers. Noelle received her bachelor’s degree in Biological Systems Engineering from UC Davis.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/noelle.png',
    location: 'University of California, Davis',
    linkedin: 'https://www.linkedin.com/in/noelle-patterson-8311b0b0/',
    github: 'https://github.com/NoellePatterson',
    email: 'nkpatterson@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 3,
    name: 'Samuel Sandoval-Solis',
    title: 'Associate Professor',
    description:
      'Samuel is an associate professor and cooperative extension specialist. His expertise is in water resources planning and management. During decision making process, Samuel is the person working between the scientists, engineers, environmentalists, system operators and decision makers; he integrates ideas into policies and quantifies benefits and drawbacks. Samuel shares his expertise and passion for quantitative water planning with students through his course entitled Water, Science and Management (ESM-121) in which he demonstrates to student tools and methods to design sustainable water resources systems.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/sam.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Samuel_Sandoval-Solis',
    email: 'samsandoval@ucdavis.edu',
    youtube: 'https://www.youtube.com/channel/UCyBwkhlzzHjVnGnDnBV5hqw',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 4,
    name: 'Colin Byrne',
    title: 'Postdoctoral Researcher',
    description:
      "Colin is a Postdoctoral Scholar at the University of California, Davis working under the guidance of Drs. Pasternack, Sandoval, and Lane. His research focuses on statistical classification of river forms and development of archetypical river morphologies to inform ecological flow management. Colin earned his PhD at the University of New Mexico where he studied flood wave hydrodynamics and hydrologic lateral surface connectivity between river channels and floodplains. Colin's research interests focus on interdisciplinary river science for improved ecological function of rivers and floodplains.",
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/colin.png',
    location: 'University of California, Davis',
    website: 'http://www.byrneriverscience.com',
    researchGate: 'https://www.researchgate.net/profile/Colin_Byrne5',
    email: 'cfbyrne@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 5,
    name: 'Hervé Guillon',
    title: 'Postdoctoral Researcher',
    description:
      'Hervé is a Postdoctoral Scholar at the University of California, Davis working with Dr. Lane and Dr. Samuel Sandoval (UC Davis) to derive a hydro-geomorphic stream classification for multiple hydrologic basins in California. He is using data mining and machine learning techniques to understand landscape and near-stream controls on channel geomorphic settings. Hervé completed his PhD in the Institut des Sciences de la Terre in France on present-day erosion processes in a glaciated catchment in the Mont-Blanc massif. Before coming to UC Davis, Hervé joined the hydrology and glaciology laboratory Institut des Géosciences de l’Environnement in France to discriminate suspended sediment origin from in-situ settling behaviour with optical methods.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/hrvg.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Herve_Guillon2',
    website: 'https://guillon.xyz',
    email: 'hguillon@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 6,
    name: 'Gregory B. Pasternack',
    title: 'Professor',
    description:
      'Greg Pasternack is a professor with two decades of interdisciplinary scientific and engineering training and experience, yielding expertise in ecogeomorphology, ecohydraulics, sediment processes, and watershed hydrology.  He leads collaborative efforts that help society manage and restore hydrogeomorphic processes in support of enhanced ecosystem functioning at local to watershed scales.  This requires a combination of basic physical and ecological science to understand how the naturally complex landscape works and then technology transfer to enable practitioners, regulators, and stakeholders to solve problems.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/greg.png',
    location: 'University of California, Davis',
    researchGate: 'https://www.researchgate.net/profile/Gregory_Pasternack',
    youtube: 'https://www.youtube.com/channel/UCAZOB4DrcgfBmH3PtySSJew',
    email: 'gpast@ucdavis.edu',
    googleScholar:
      'https://scholar.google.com/citations?hl=en&user=PSIXjQoAAAAJ',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 7,
    name: 'Sarah Yarnell',
    title: 'Senior Researcher',
    description:
      'Sarah is an Associate Project Scientist at the Center for Watershed Sciences.  Her studies focus on integrating the traditional fields of hydrology, ecology and geomorphology in the river environment.  She is currently conducting research that applies understanding of river ecosystem processes to managed systems in the Sierra Nevada, with a focus on the development and maintenance of riverine habitat.  She is a recognized expert in the ecology of the Foothill yellow-legged frog (Rana boylii), a California species of special concern, and she is the first researcher to apply sediment transport and two-dimensional hydrodynamic modeling techniques to the evaluation of instream amphibian habitat.  Her experience includes consultation as a technical expert for various hydroelectric power relicensing projects (Big Creek Project, Desabla-Centerville Project, Middle Fork American Project, Yuba-Bear/Drum-Spaulding Project, Spring Gap-Stanislaus), where she has work closely with government resource agencies and the private sector to assess the impacts of environmental flows on aquatic biota and provide recommendations for developing flows that improve the functioning of river ecosystems. More recently, her experience has expanded to include evaluation and restoration of headwater systems, particularly montane meadows in the Sierra Nevada and Cascade ranges.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'University of California, Davis',
    linkedin: 'https://www.linkedin.com/in/sarah-yarnell-28617317/',
    email: 'smyarnell@ucdavis.edu',
    researchGate:
      'https://www.researchgate.net/scientific-contributions/2004963786_Sarah_M_Yarnell',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 8,
    name: 'Leo Qiu',
    title: 'Software Engineer',
    description:
      'Leo is a full stack software developer working with Python and Javascript. As a web developer and programmer for the eFlows project, Leo works to communicate environmental data in clear and interactive platform.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/leo.png',
    location: 'Port 3000',
    github: 'https://github.com/leogoesger',
    website: 'https://leogoesger.io/',
    linkedin: 'https://www.linkedin.com/in/leo-qiu/',
    researchGate: '',
    youtube: '',
    email: 'leoqiu@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 9,
    name: 'Daren M Carlisle',
    title: 'Ecological Studies Coordinator',
    location: 'U.S. Geological Survey',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    linkedin: '',
    email: 'dcarlisle@usgs.gov',
    googleScholar:
      'https://scholar.google.com/citations?user=EsneVgkAAAAJ&hl=en',
    researchGate: 'https://www.researchgate.net/profile/Daren_Carlisle',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 10,
    name: 'Jose Pablo Ortiz Partida',
    title: 'Ph.D. Candidate',
    description:
      'Jose Pablo received a scholarship from the Mexican Government for pursuing a Ph.D. in Hydrologic Sciences at the University of California, Davis. He is interested on Integrated Water Resources Management with an specific focus on water quantity and water quality modelling. He earned his Bachelor’s degree in Environmental Engineering from the Western Institute of Technology and Higher Education (ITESO) in Guadalajara, Jalisco, Mexico. He is working on a water quality modeling for the Big Bend reach of the Rio Grande/Rio Bravo Basin. His dream is to find solutions for the preservation and distribution of water resources to provide people in need access to clean and safe water.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/pablo.png',
    location: 'University of California, Davis',
    researchGate:
      'https://www.researchgate.net/profile/Jose_Pablo_Ortiz_Partida',
    email: 'joportiz@ucdavis.edu',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 11,
    name: 'Ted Grantham',
    title: 'Cooperative Extension Specialist',
    description:
      'Ted is an Assistant Cooperative Extension Specialist with the University of California Division of Agriculture and Natural Resources (ANR) and Adjunct Assistant Professor on the faculty of the Department of Environmental Science, Policy, and Management at U.C. Berkeley. A primary research focus is understanding environmental water needs and identifying strategies for incorporating ecological principles in the management of water resources.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/ted.png',
    location: 'University of California, Berkeley',
    website: 'https://nature.berkeley.edu/granthamlab/',
    email: 'tgrantham@berkeley.edu',
    researchGate: 'https://www.researchgate.net/profile/Theodore_Ted_Grantham',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 12,
    name: 'Julie Zimmerman',
    title: 'Lead Scientist',
    description:
      'Julie is the lead freshwater scientist at the Nature Conservancy. Her main focus in The Nature Conservancy’s California Chapter is to develop collaborative, science-based approaches to water management and river restoration in California, based on principles of decision science. Julie has over 10 years of experience in the area of environmental flows, providing scientific leadership and technical expertise through positions with the Conservancy, the federal government, and academia. Julie is currently working with academic and agency partners to develop environmental flow recommendations for every stream in California and a companion framework to refine these flow recommendations with local information where necessary.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'The Nature Conservancy',
    website: 'https://www.scienceforconservation.org/our-team/julie-zimmerman',
    email: 'julie.zimmerman@tnc.org',
    researchGate: 'https://www.researchgate.net/profile/Julie_Zimmerman4',
    linkedin: 'https://www.linkedin.com/in/julie-zimmerman-81268657',
    googleScholar:
      'https://scholar.google.com/citations?user=EkchY6kAAAAJ&hl=en&citsig=AMstHGSvNie8iYWpLl7wF8Li73joZkqAkA',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 13,
    name: 'Alyssa Obester',
    title: 'Research Specialist',
    description:
      'Alyssa is a research specialist at the Center for Watershed Sciences. She in broadly interested in environmental flows, river restoration, and Western water management. For her master’s thesis, she developed restoration recommendations and quantified the economic benefits of restoring the Lower Yuba River. Alyssa holds a M.S. in Environmental Science and Management with an emphasis in Water Resources from the Bren School at UC Santa Barbara, and a B.S. in Environmental Science and Management from UC Davis.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/alyssa.png',
    location: 'University of California, Davis',
    website: '',
    email: 'anobester@ucdavis.edu',
    researchGate: '',
    linkedin: 'https://www.linkedin.com/in/alyssaobester',
    googleScholar: '',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 14,
    name: 'Jeanette Howard',
    title: 'Director of Science',
    description:
      'Jeanette leads TNC’s freshwater science team in The Nature Conservancy’s California Chapter. The team focuses on developing and fostering a science enterprise to sustain healthy aquatic ecosystems in California. This work includes conservation planning for freshwater biodiversity, defining environmental flows to maintain and restore freshwater species, habitat and ecological processes, deepening our understanding of groundwater dependent ecosystems, and building partnerships for conservation actions. Jeanette is currently working on a freshwater conservation blueprint for California to identify freshwater hotspots.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'The Nature Conservancy',
    website: 'https://www.scienceforconservation.org/our-team/jeanette-howard',
    email: 'jeanette.howard@tnc.org',
    researchGate: '',
    linkedin: 'https://www.linkedin.com/in/jeanette-howard-6557b15/',
    googleScholar: '',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 15,
    name: 'Robert Lusardi',
    title: 'Senior Researcher',
    description:
      'Dr. Lusardi is an aquatic research ecologist at the Center for Watershed Sciences and is the California Trout-UC Davis Wild and Coldwater Fish Scientist. Rob is broadly interested in stream ecology and food web dynamics of rivers throughout California and their role in shaping salmonid response. His research examines interactions between water temperature and food availability on the growth and survival of juvenile salmon, how different habitat types influence the costs and benefits of juvenile salmonid rearing, the conservation implications of different salmonid reintroduction strategies, and the status and conservation of salmonids throughout California.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'University of California, Davis',
    website: 'https://watershed.ucdavis.edu/people/rlusardi',
    email: 'ralusardi@ucdavis.edu',
    researchGate: 'https://www.researchgate.net/profile/Robert_Lusardi',
    linkedin: '',
    googleScholar: '',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 16,
    name: 'Eric Stein',
    title: 'Principal Scientist',
    description:
      "Eric Stein is the head of SCCWRP's Biology Department, where he oversees a variety of projects related to in-stream and coastal water quality, hydromodification, ecohydrology, development of biological indices, and assessment of wetlands and other aquatic resources. He received his B.S. in biology in 1987, M.Ed. in science education in 1988, and doctorate degree in environmental science and engineering in 1995, all from the University of California, Los Angeles. Dr. Stein joined SCCWRP in 2002.",
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'Southern California Coastal Water Research Project',
    website: 'http://www.sccwrp.org/AboutSCCWRP/SCCWRPStaff/SteinEric.aspx',
    email: 'erics@sccwrp.org',
    researchGate: 'https://www.researchgate.net/profile/Eric_Stein',
    linkedin: '',
    googleScholar:
      'https://scholar.google.com/citations?user=npUacLIAAAAJ&hl=en',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
  {
    id: 17,
    name: 'Larry Brown',
    title: 'Research Biologist',
    description:
      'Larry R. Brown is a Research Biologist with the U.S. Geological Survey, California Water Science Center. Dr. Brown has over 35 years experience working in California aquatic systems. He is a recognized expert on the ecology of California fishes and has published on California fishes, benthic macroinvertebrates and benthic algae. Dr. Brown is currently involved in studies of the effects of climate change on selected fish species in the Central Valley watershed and San Francisco Estuary, factors associated with declines in pelagic fish populations of the San Francisco Estuary, and effects of hydrologic alteration on California stream systems. In the course of his work, Dr. Brown has authored or coauthored over 80 scientific articles and reports.',
    image: 'https://s3-us-west-1.amazonaws.com/funcflow/resources/default.png',
    location: 'U.S. Geological Survey',
    website:
      'https://www.usgs.gov/staff-profiles/larry-brown?qt-staff_profile_science_products=3#qt-staff_profile_science_products',
    email: 'lrbrown@usgs.gov',
    researchGate: 'https://www.researchgate.net/profile/Larry_Brown5',
    linkedin: '',
    googleScholar:
      'https://scholar.google.com/citations?user=ARp-sfYAAAAJ&hl=en',
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
];
